require "prct07/version"
require "prct07/preg"
require "prct07/simple_expec"
require "prct07/verd_fals"
require "prct07/lista_doble"
require "prct07/inter_user"
require "prct07/exam"
require "prct07/quiz"
